/// Flutter icons Custom_Icon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom_Icon
///      fonts:
///       - asset: fonts/Custom_Icon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Custom_Icon {
  Custom_Icon._();

  static const _kFontFam = 'Custom_Icon';
  static const String? _kFontPkg = null;

  static const IconData youtube_svgrepo_com = IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
